version: '3'
services:
  api:
    build: ./
    depends_on:
      - db
    container_name: 'api'
    ports:
      - '80:80'
    volumes:
      - './html/central-system-api:/var/www/'
      - './conf/000-default.conf:/etc/apache2/sites-available/000-default.conf'
    networks:
      net:
        ipv4_address: 172.31.0.2
  db:
    build: ./mysql/
    container_name: 'mysql-system'
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3333:3306'
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=xxxx
      - MYSQL_DATABASE=central
      - MYSQL_USER=user
      - MYSQL_PASSWORD=xxxx
    networks:
      net:
        ipv4_address: 172.31.0.3
networks: 
  net:
    ipam:
      driver: default
      config: 
        - subnet: "172.31.0.0/24"

